const Stack = require('./stack.js');
const stack = new Stack(5);
stack.push(2);
stack.push(5);
stack.push(7);
stack.pop();
stack.push(1);
stack.pop();
stack.pop();
stack.peek();
stack.push(15);
stack.push(7);
stack.push(4);
stack.push(78);
stack.printStack();
console.log(stack);